# fly.toml app configuration file generated for tsoha-visitors-mko on 2024-01-05T14:01:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tsoha-visitors-mko"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
